export const ANNOUNCEMENT_TEMPLATE_GROUPS = [
  { id: 'all', label: 'All templates' },
  { id: 'header', label: 'Header' },
  { id: 'homepage', label: 'Homepage' },
  { id: 'product', label: 'Product pages' },
  { id: 'categories', label: 'Categories' },
  { id: 'checkout', label: 'Checkout' },
  { id: 'global', label: 'All pages' },
  { id: 'section', label: 'Sections' },
];

export const ANNOUNCEMENT_TEMPLATES = [
  {
    key: 'header-free-shipping',
    label: 'Free shipping strip',
    description: 'Compact top bar for threshold-based shipping updates.',
    group: 'header',
    displayLocation: 'HEADER',
    displayStyle: 'BANNER',
    variant: 'bar',
    theme: 'sky',
    tags: ['shipping', 'utility', 'top bar'],
    defaults: {
      title: 'Free shipping over $99',
      content: '',
      type: 'info',
      displayLocation: 'HEADER',
      displayStyle: 'BANNER',
      priority: 72,
      buttonText: 'Shop now',
      buttonLink: '/products',
    },
  },
  {
    key: 'header-flash-sale',
    label: 'Flash sale header',
    description: 'Urgent top-of-site promo with a tight CTA.',
    group: 'header',
    displayLocation: 'HEADER',
    displayStyle: 'BANNER',
    variant: 'coupon',
    theme: 'ember',
    tags: ['sale', 'urgency', 'countdown'],
    defaults: {
      title: 'Flash sale ends tonight',
      content: '',
      type: 'promotion',
      displayLocation: 'HEADER',
      displayStyle: 'BANNER',
      priority: 94,
      buttonText: 'Claim offer',
      buttonLink: '/search?q=sale',
    },
  },
  {
    key: 'header-trust-strip',
    label: 'Trust bar',
    description: 'High-confidence header for support, returns, and delivery promises.',
    group: 'header',
    displayLocation: 'HEADER',
    displayStyle: 'BANNER',
    variant: 'trust',
    theme: 'graphite',
    tags: ['trust', 'returns', 'support'],
    defaults: {
      title: '30-day returns and live support',
      content: '',
      type: 'feature',
      displayLocation: 'HEADER',
      displayStyle: 'BANNER',
      priority: 60,
      buttonText: 'View policies',
      buttonLink: '/returns',
    },
  },
  {
    key: 'header-store-hours',
    label: 'Store hours strip',
    description: 'Operational top bar for delivery windows or support availability.',
    group: 'header',
    displayLocation: 'HEADER',
    displayStyle: 'BANNER',
    variant: 'minimal',
    theme: 'amber',
    tags: ['operations', 'hours', 'support'],
    defaults: {
      title: 'Support is online until 10 PM',
      content: '',
      type: 'info',
      displayLocation: 'HEADER',
      displayStyle: 'BANNER',
      priority: 65,
      buttonText: 'Contact us',
      buttonLink: '/contact',
    },
  },
  {
    key: 'header-category-dropdown-highlight',
    label: 'Category dropdown highlight',
    description: 'Announcement banner shown only inside the categories dropdown menu.',
    group: 'header',
    displayLocation: 'CATEGORY_DROPDOWN',
    displayStyle: 'BANNER',
    variant: 'menu',
    theme: 'graphite',
    tags: ['header', 'categories', 'dropdown'],
    defaults: {
      title: 'Seasonal categories are live',
      content: 'Highlight a new collection or seasonal drop in the categories menu.',
      type: 'feature',
      displayLocation: 'CATEGORY_DROPDOWN',
      displayStyle: 'BANNER',
      priority: 66,
      buttonText: 'Shop the edit',
      buttonLink: '/products',
    },
  },
  {
    key: 'homepage-hero-promo',
    label: 'Hero campaign banner',
    description: 'Large homepage campaign banner with strong CTA treatment.',
    group: 'homepage',
    displayLocation: 'HOMEPAGE',
    displayStyle: 'BANNER',
    variant: 'hero',
    theme: 'ocean',
    tags: ['hero', 'campaign', 'homepage'],
    defaults: {
      title: 'New season campaign is live',
      content: 'Lead the homepage with a high-contrast campaign message.',
      type: 'promotion',
      displayLocation: 'HOMEPAGE',
      displayStyle: 'BANNER',
      priority: 92,
      buttonText: 'Explore campaign',
      buttonLink: '/products',
    },
  },
  {
    key: 'homepage-editorial-feature',
    label: 'Editorial feature',
    description: 'Story-led homepage announcement for brand launches and feature education.',
    group: 'homepage',
    displayLocation: 'HOMEPAGE',
    displayStyle: 'BANNER',
    variant: 'editorial',
    theme: 'graphite',
    tags: ['storytelling', 'feature', 'homepage'],
    defaults: {
      title: 'Behind the collection',
      content: 'Use a richer homepage slot when the announcement needs context.',
      type: 'feature',
      displayLocation: 'HOMEPAGE',
      displayStyle: 'BANNER',
      priority: 68,
      buttonText: 'Read the story',
      buttonLink: '/about',
    },
  },
  {
    key: 'homepage-new-arrivals',
    label: 'New arrivals spotlight',
    description: 'Homepage banner focused on fresh inventory or category launches.',
    group: 'homepage',
    displayLocation: 'HOMEPAGE',
    displayStyle: 'BANNER',
    variant: 'split',
    theme: 'emerald',
    tags: ['new arrivals', 'catalog', 'homepage'],
    defaults: {
      title: 'New arrivals just landed',
      content: 'Push repeat visitors toward the latest drop fast.',
      type: 'product',
      displayLocation: 'HOMEPAGE',
      displayStyle: 'BANNER',
      priority: 77,
      buttonText: 'Shop new arrivals',
      buttonLink: '/products?sort=newest',
    },
  },
  {
    key: 'homepage-coupon-modal',
    label: 'Homepage coupon modal',
    description: 'Welcome-style modal for first-order offers or newsletter capture.',
    group: 'homepage',
    displayLocation: 'HOMEPAGE',
    displayStyle: 'MODAL',
    variant: 'coupon',
    theme: 'ember',
    tags: ['coupon', 'homepage', 'signup'],
    defaults: {
      title: 'Take 10% off your first order',
      content: 'Best used for homepage traffic that needs a conversion nudge.',
      type: 'promotion',
      displayLocation: 'HOMEPAGE',
      displayStyle: 'MODAL',
      priority: 84,
      buttonText: 'Unlock discount',
      buttonLink: '/register',
    },
  },
  {
    key: 'homepage-giveaway-slide-in',
    label: 'Giveaway slide-in',
    description: 'Non-blocking giveaway or waitlist prompt for homepage visitors.',
    group: 'homepage',
    displayLocation: 'HOMEPAGE',
    displayStyle: 'SLIDE_IN',
    variant: 'offer',
    theme: 'sunset',
    tags: ['giveaway', 'slide in', 'homepage'],
    defaults: {
      title: 'Enter the monthly giveaway',
      content: 'Keep the homepage browsable while still surfacing the campaign.',
      type: 'promotion',
      displayLocation: 'HOMEPAGE',
      displayStyle: 'SLIDE_IN',
      priority: 73,
      buttonText: 'Enter now',
      buttonLink: '/contact',
    },
  },
  {
    key: 'homepage-community-sticky',
    label: 'Community sticky',
    description: 'Persistent bottom bar for community events, livestreams, or launches.',
    group: 'homepage',
    displayLocation: 'HOMEPAGE',
    displayStyle: 'STICKY',
    variant: 'community',
    theme: 'amethyst',
    tags: ['sticky', 'community', 'event'],
    defaults: {
      title: 'Live product workshop starts at 7 PM',
      content: 'Use a persistent sticky bar for events with a clear next action.',
      type: 'feature',
      displayLocation: 'HOMEPAGE',
      displayStyle: 'STICKY',
      priority: 79,
      buttonText: 'Reserve a seat',
      buttonLink: '/blog',
    },
  },
  {
    key: 'homepage-welcome-popup',
    label: 'Homepage welcome popup',
    description: 'Homepage-only popup for capture offers or quick orientation.',
    group: 'homepage',
    displayLocation: 'HOMEPAGE',
    displayStyle: 'POPUP',
    variant: 'welcome',
    theme: 'ocean',
    tags: ['welcome', 'popup', 'homepage'],
    defaults: {
      title: 'Welcome! Take 10% off today',
      content: 'Share a quick offer or signup incentive before shoppers dive in.',
      type: 'promotion',
      displayLocation: 'HOMEPAGE',
      displayStyle: 'POPUP',
      priority: 81,
      buttonText: 'Claim offer',
      buttonLink: '/register',
    },
  },
  {
    key: 'product-restock-alert',
    label: 'Restock banner',
    description: 'Product-page announcement for replenishment or back-in-stock events.',
    group: 'product',
    displayLocation: 'PRODUCT_PAGES',
    displayStyle: 'BANNER',
    variant: 'bar',
    theme: 'emerald',
    tags: ['restock', 'product', 'inventory'],
    defaults: {
      title: 'Best-seller restocked this week',
      content: 'Create urgency close to the product decision point.',
      type: 'product',
      displayLocation: 'PRODUCT_PAGES',
      displayStyle: 'BANNER',
      priority: 74,
      buttonText: 'Browse best sellers',
      buttonLink: '/products',
    },
  },
  {
    key: 'product-bundle-offer',
    label: 'Bundle upsell banner',
    description: 'Cross-sell banner for product bundles and add-on campaigns.',
    group: 'product',
    displayLocation: 'PRODUCT_PAGES',
    displayStyle: 'BANNER',
    variant: 'split',
    theme: 'ocean',
    tags: ['bundle', 'upsell', 'product'],
    defaults: {
      title: 'Bundle and save on matching essentials',
      content: 'Use on product pages when the message should feel adjacent to the item.',
      type: 'promotion',
      displayLocation: 'PRODUCT_PAGES',
      displayStyle: 'BANNER',
      priority: 71,
      buttonText: 'See bundle',
      buttonLink: '/search?q=bundle',
    },
  },
  {
    key: 'product-low-stock-slide',
    label: 'Low-stock slide-in',
    description: 'Slide-in urgency cue for inventory-sensitive product pages.',
    group: 'product',
    displayLocation: 'PRODUCT_PAGES',
    displayStyle: 'SLIDE_IN',
    variant: 'minimal',
    theme: 'ember',
    tags: ['low stock', 'slide in', 'product'],
    defaults: {
      title: 'Low stock on top variants',
      content: 'A lightweight urgency pattern for shoppers already evaluating the product.',
      type: 'promotion',
      displayLocation: 'PRODUCT_PAGES',
      displayStyle: 'SLIDE_IN',
      priority: 83,
      buttonText: 'View options',
      buttonLink: '/products',
    },
  },
  {
    key: 'product-size-guide-popup',
    label: 'Fit guidance popup',
    description: 'Popup for fit, sizing, or product education at the point of consideration.',
    group: 'product',
    displayLocation: 'PRODUCT_PAGES',
    displayStyle: 'POPUP',
    variant: 'checklist',
    theme: 'graphite',
    tags: ['education', 'fit', 'popup'],
    defaults: {
      title: 'Need help choosing the right fit?',
      content: 'Use a popup when the announcement needs a little more explanation.',
      type: 'feature',
      displayLocation: 'PRODUCT_PAGES',
      displayStyle: 'POPUP',
      priority: 67,
      buttonText: 'Open size guide',
      buttonLink: '/size-guide',
    },
  },
  {
    key: 'product-detail-modal',
    label: 'Product detail modal',
    description: 'Modal for deeper product education or care guidance without leaving the page.',
    group: 'product',
    displayLocation: 'PRODUCT_PAGES',
    displayStyle: 'MODAL',
    variant: 'spotlight',
    theme: 'ocean',
    tags: ['product', 'modal', 'education'],
    defaults: {
      title: 'Sizing & care details',
      content: 'Share extra context that helps shoppers feel confident before purchase.',
      type: 'feature',
      displayLocation: 'PRODUCT_PAGES',
      displayStyle: 'MODAL',
      priority: 72,
      buttonText: 'View size guide',
      buttonLink: '/size-guide',
    },
  },
  {
    key: 'product-assurance-sticky',
    label: 'Product assurance sticky',
    description: 'Persistent reassurance bar for returns, shipping, or guarantees on product pages.',
    group: 'product',
    displayLocation: 'PRODUCT_PAGES',
    displayStyle: 'STICKY',
    variant: 'trust',
    theme: 'graphite',
    tags: ['product', 'sticky', 'trust'],
    defaults: {
      title: 'Free returns on every product',
      content: 'Keep reassurance visible while shoppers compare options.',
      type: 'feature',
      displayLocation: 'PRODUCT_PAGES',
      displayStyle: 'STICKY',
      priority: 70,
      buttonText: 'Read returns',
      buttonLink: '/returns',
    },
  },
  {
    key: 'category-hero-banner',
    label: 'Category highlight banner',
    description: 'Banner for category pages to spotlight collections or promos.',
    group: 'categories',
    displayLocation: 'CATEGORIES',
    displayStyle: 'BANNER',
    variant: 'hero',
    theme: 'emerald',
    tags: ['category', 'banner', 'collection'],
    defaults: {
      title: 'Explore the featured collection',
      content: 'Add context for this category and highlight key picks.',
      type: 'feature',
      displayLocation: 'CATEGORIES',
      displayStyle: 'BANNER',
      priority: 70,
      buttonText: 'Shop featured',
      buttonLink: '/products',
    },
  },
  {
    key: 'category-discovery-popup',
    label: 'Category discovery popup',
    description: 'Popup for category-specific offers or quick guides.',
    group: 'categories',
    displayLocation: 'CATEGORIES',
    displayStyle: 'POPUP',
    variant: 'spotlight',
    theme: 'ocean',
    tags: ['category', 'popup', 'offer'],
    defaults: {
      title: 'Save on this category',
      content: 'Offer a quick incentive or guide for category shoppers.',
      type: 'promotion',
      displayLocation: 'CATEGORIES',
      displayStyle: 'POPUP',
      priority: 74,
      buttonText: 'View deals',
      buttonLink: '/search?q=deal',
    },
  },
  {
    key: 'category-guide-modal',
    label: 'Category guide modal',
    description: 'Modal for deeper category education or fit guidance.',
    group: 'categories',
    displayLocation: 'CATEGORIES',
    displayStyle: 'MODAL',
    variant: 'checklist',
    theme: 'graphite',
    tags: ['category', 'modal', 'guide'],
    defaults: {
      title: 'Need help choosing?',
      content: 'Share buying tips or category guidance.',
      type: 'feature',
      displayLocation: 'CATEGORIES',
      displayStyle: 'MODAL',
      priority: 68,
      buttonText: 'Read guide',
      buttonLink: '/size-guide',
    },
  },
  {
    key: 'category-offer-slide-in',
    label: 'Category offer slide-in',
    description: 'Slide-in nudges for category promotions.',
    group: 'categories',
    displayLocation: 'CATEGORIES',
    displayStyle: 'SLIDE_IN',
    variant: 'offer',
    theme: 'sunset',
    tags: ['category', 'slide in', 'promo'],
    defaults: {
      title: 'Limited-time category offer',
      content: 'Highlight a short-lived promotion for this category.',
      type: 'promotion',
      displayLocation: 'CATEGORIES',
      displayStyle: 'SLIDE_IN',
      priority: 76,
      buttonText: 'Shop offer',
      buttonLink: '/products',
    },
  },
  {
    key: 'category-assurance-sticky',
    label: 'Category assurance sticky',
    description: 'Sticky reassurance bar for category browsing.',
    group: 'categories',
    displayLocation: 'CATEGORIES',
    displayStyle: 'STICKY',
    variant: 'trust',
    theme: 'graphite',
    tags: ['category', 'sticky', 'trust'],
    defaults: {
      title: 'Free returns on this collection',
      content: 'Keep reassurance visible as shoppers explore.',
      type: 'feature',
      displayLocation: 'CATEGORIES',
      displayStyle: 'STICKY',
      priority: 65,
      buttonText: 'View policy',
      buttonLink: '/returns',
    },
  },
  {
    key: 'checkout-shipping-deadline',
    label: 'Shipping deadline bar',
    description: 'Checkout banner for shipping cutoffs and holiday delivery expectations.',
    group: 'checkout',
    displayLocation: 'CHECKOUT',
    displayStyle: 'BANNER',
    variant: 'coupon',
    theme: 'amber',
    tags: ['checkout', 'shipping', 'deadline'],
    defaults: {
      title: 'Order within 2 hours for same-day dispatch',
      content: 'Useful when cutoff timing matters during checkout.',
      type: 'info',
      displayLocation: 'CHECKOUT',
      displayStyle: 'BANNER',
      priority: 89,
      countdownEnabled: true,
    },
  },
  {
    key: 'checkout-support-popup',
    label: 'Checkout support popup',
    description: 'Focused popup for last-minute help or reassurance at checkout.',
    group: 'checkout',
    displayLocation: 'CHECKOUT',
    displayStyle: 'POPUP',
    variant: 'support',
    theme: 'amber',
    tags: ['checkout', 'popup', 'support'],
    defaults: {
      title: 'Questions before you pay?',
      content: 'Share support options or key policies right before purchase.',
      type: 'info',
      displayLocation: 'CHECKOUT',
      displayStyle: 'POPUP',
      priority: 72,
      buttonText: 'Contact support',
      buttonLink: '/help',
    },
  },
  {
    key: 'checkout-upsell-modal',
    label: 'Checkout upsell modal',
    description: 'Modal for gift wrap, add-ons, or order protection before payment.',
    group: 'checkout',
    displayLocation: 'CHECKOUT',
    displayStyle: 'MODAL',
    variant: 'spotlight',
    theme: 'emerald',
    tags: ['checkout', 'upsell', 'modal'],
    defaults: {
      title: 'Add gift wrap before you place the order',
      content: 'Use sparingly for upsells that genuinely help the checkout flow.',
      type: 'promotion',
      displayLocation: 'CHECKOUT',
      displayStyle: 'MODAL',
      priority: 66,
      buttonText: 'Add extras',
      buttonLink: '/cart',
    },
  },
  {
    key: 'checkout-support-slide',
    label: 'Checkout help slide-in',
    description: 'Slide-in assistance for last-minute checkout questions.',
    group: 'checkout',
    displayLocation: 'CHECKOUT',
    displayStyle: 'SLIDE_IN',
    variant: 'minimal',
    theme: 'ocean',
    tags: ['checkout', 'help', 'slide in'],
    defaults: {
      title: 'Need help before paying?',
      content: 'Point shoppers to help resources without blocking checkout.',
      type: 'info',
      displayLocation: 'CHECKOUT',
      displayStyle: 'SLIDE_IN',
      priority: 74,
      buttonText: 'Open help',
      buttonLink: '/help',
    },
  },
  {
    key: 'checkout-trust-sticky',
    label: 'Checkout trust sticky',
    description: 'Persistent bottom bar for payment security or guarantee messaging.',
    group: 'checkout',
    displayLocation: 'CHECKOUT',
    displayStyle: 'STICKY',
    variant: 'trust',
    theme: 'graphite',
    tags: ['checkout', 'trust', 'sticky'],
    defaults: {
      title: 'Secure checkout with order protection',
      content: 'Use this when reassurance is more important than urgency.',
      type: 'feature',
      displayLocation: 'CHECKOUT',
      displayStyle: 'STICKY',
      priority: 76,
      buttonText: 'Review policy',
      buttonLink: '/privacy',
    },
  },
  {
    key: 'checkout-payment-maintenance',
    label: 'Payment maintenance notice',
    description: 'Operational checkout message for gateway issues or payment windows.',
    group: 'checkout',
    displayLocation: 'CHECKOUT',
    displayStyle: 'STICKY',
    variant: 'operational',
    theme: 'amber',
    tags: ['checkout', 'maintenance', 'ops'],
    defaults: {
      title: 'Some payment methods are temporarily unavailable',
      content: 'Keep shoppers informed while steering them to available options.',
      type: 'maintenance',
      displayLocation: 'CHECKOUT',
      displayStyle: 'STICKY',
      priority: 97,
      buttonText: 'Need help?',
      buttonLink: '/help',
    },
  },
  {
    key: 'global-brand-story',
    label: 'Brand story banner',
    description: 'All-pages banner for broad campaigns or brand positioning.',
    group: 'global',
    displayLocation: 'ALL',
    displayStyle: 'BANNER',
    variant: 'editorial',
    theme: 'amethyst',
    tags: ['brand', 'all pages', 'story'],
    defaults: {
      title: 'Crafted for everyday routines',
      content: 'Use an all-pages campaign when the whole site should feel aligned.',
      type: 'feature',
      displayLocation: 'ALL',
      displayStyle: 'BANNER',
      priority: 58,
      buttonText: 'Read our story',
      buttonLink: '/about',
    },
  },
  {
    key: 'global-app-download',
    label: 'App download popup',
    description: 'Sitewide popup for app installs, SMS opt-ins, or loyalty capture.',
    group: 'global',
    displayLocation: 'ALL',
    displayStyle: 'POPUP',
    variant: 'spotlight',
    theme: 'ocean',
    tags: ['app', 'popup', 'all pages'],
    defaults: {
      title: 'Install the app for member-only drops',
      content: 'Reach visitors anywhere in the storefront with a consistent message.',
      type: 'promotion',
      displayLocation: 'ALL',
      displayStyle: 'POPUP',
      priority: 75,
      buttonText: 'Get the app',
      buttonLink: '/login',
    },
  },
  {
    key: 'global-support-banner',
    label: 'Support and policy bar',
    description: 'Sitewide support message with room for operational updates.',
    group: 'global',
    displayLocation: 'ALL',
    displayStyle: 'BANNER',
    variant: 'trust',
    theme: 'graphite',
    tags: ['support', 'policy', 'all pages'],
    defaults: {
      title: 'Questions before ordering?',
      content: 'Make help easy to find on any page.',
      type: 'info',
      displayLocation: 'ALL',
      displayStyle: 'BANNER',
      priority: 51,
      buttonText: 'Contact support',
      buttonLink: '/contact',
    },
  },
  {
    key: 'global-help-slide-in',
    label: 'Global help slide-in',
    description: 'Sitewide slide-in for support, campaigns, or updates.',
    group: 'global',
    displayLocation: 'ALL',
    displayStyle: 'SLIDE_IN',
    variant: 'help',
    theme: 'graphite',
    tags: ['all pages', 'slide in', 'support'],
    defaults: {
      title: 'Need help finding something?',
      content: 'Guide shoppers to support without interrupting their flow.',
      type: 'info',
      displayLocation: 'ALL',
      displayStyle: 'SLIDE_IN',
      priority: 62,
      buttonText: 'Open help',
      buttonLink: '/help',
    },
  },
  {
    key: 'global-newsletter-modal',
    label: 'Newsletter modal',
    description: 'Sitewide modal for list building or loyalty signup.',
    group: 'global',
    displayLocation: 'ALL',
    displayStyle: 'MODAL',
    variant: 'spotlight',
    theme: 'amethyst',
    tags: ['all pages', 'modal', 'signup'],
    defaults: {
      title: 'Join the insiders list',
      content: 'Share launches, early access, and reward updates across the storefront.',
      type: 'promotion',
      displayLocation: 'ALL',
      displayStyle: 'MODAL',
      priority: 72,
      buttonText: 'Join now',
      buttonLink: '/register',
    },
  },
  {
    key: 'global-seasonal-campaign',
    label: 'Seasonal sticky campaign',
    description: 'Persistent sitewide campaign for major seasonal promotions.',
    group: 'global',
    displayLocation: 'ALL',
    displayStyle: 'STICKY',
    variant: 'community',
    theme: 'sunset',
    tags: ['seasonal', 'sticky', 'all pages'],
    defaults: {
      title: 'Holiday gifting week is live',
      content: 'A sitewide sticky format for the campaigns you want everywhere.',
      type: 'promotion',
      displayLocation: 'ALL',
      displayStyle: 'STICKY',
      priority: 91,
      buttonText: 'Browse gifting',
      buttonLink: '/gift-cards',
      countdownEnabled: true,
    },
  },
  {
    key: 'section-collection-highlight',
    label: 'Collection section banner',
    description: 'Targeted homepage section banner for collection storytelling.',
    group: 'section',
    displayLocation: 'SECTION',
    displayStyle: 'BANNER',
    variant: 'hero',
    theme: 'emerald',
    tags: ['section', 'collection', 'homepage'],
    defaults: {
      title: 'Featured collection of the week',
      content: 'Drop a campaign directly above a specific homepage section.',
      type: 'product',
      displayLocation: 'SECTION',
      displayStyle: 'BANNER',
      priority: 69,
      buttonText: 'Shop collection',
      buttonLink: '/products',
      sectionId: '',
    },
  },
  {
    key: 'section-category-launch',
    label: 'Category launch banner',
    description: 'Homepage section-specific launch banner with a strong CTA.',
    group: 'section',
    displayLocation: 'SECTION',
    displayStyle: 'BANNER',
    variant: 'split',
    theme: 'ocean',
    tags: ['section', 'launch', 'category'],
    defaults: {
      title: 'New category just opened',
      content: 'Use this for category launches mapped to a homepage section.',
      type: 'promotion',
      displayLocation: 'SECTION',
      displayStyle: 'BANNER',
      priority: 82,
      buttonText: 'View launch',
      buttonLink: '/products',
      sectionId: '',
    },
  },
  {
    key: 'section-featured-collections-card',
    label: 'Featured collections card',
    description: 'Card-style spotlight that mirrors the featured collections callout.',
    group: 'section',
    displayLocation: 'SECTION',
    displayStyle: 'BANNER',
    variant: 'feature-card',
    theme: 'ocean',
    tags: ['section', 'card', 'featured'],
    defaults: {
      title: 'Featured Collections',
      content: 'Keep your category navigation dynamic while highlighting current campaigns.',
      type: 'promotion',
      displayLocation: 'SECTION',
      displayStyle: 'BANNER',
      priority: 86,
      buttonText: 'Explore deals',
      buttonLink: '/search?q=sale',
      sectionId: '',
    },
  },
  {
    key: 'section-seasonal-card',
    label: 'Seasonal highlight card',
    description: 'Warm seasonal card for limited-time collections and edits.',
    group: 'section',
    displayLocation: 'SECTION',
    displayStyle: 'BANNER',
    variant: 'feature-card',
    theme: 'sunset',
    tags: ['section', 'seasonal', 'card'],
    defaults: {
      title: 'Seasonal edit is live',
      content: 'Share a curated seasonal assortment right above the target section.',
      type: 'promotion',
      displayLocation: 'SECTION',
      displayStyle: 'BANNER',
      priority: 78,
      buttonText: 'Shop the edit',
      buttonLink: '/products',
      sectionId: '',
    },
  },
  {
    key: 'section-community-card',
    label: 'Community drop card',
    description: 'Community-driven feature card for drops, events, or launches.',
    group: 'section',
    displayLocation: 'SECTION',
    displayStyle: 'BANNER',
    variant: 'feature-card',
    theme: 'amethyst',
    tags: ['section', 'community', 'card'],
    defaults: {
      title: 'Community drop starts now',
      content: 'Use for member-exclusive launches tied to a specific section.',
      type: 'feature',
      displayLocation: 'SECTION',
      displayStyle: 'BANNER',
      priority: 80,
      buttonText: 'Join the drop',
      buttonLink: '/products',
      sectionId: '',
    },
  },
  {
    key: 'section-editorial-card',
    label: 'Editorial story card',
    description: 'Editorial card for storytelling tied to a specific homepage section.',
    group: 'section',
    displayLocation: 'SECTION',
    displayStyle: 'BANNER',
    variant: 'feature-card',
    theme: 'graphite',
    tags: ['section', 'editorial', 'card'],
    defaults: {
      title: 'Inside the collection',
      content: 'Add a story-driven card to give context before the section content.',
      type: 'feature',
      displayLocation: 'SECTION',
      displayStyle: 'BANNER',
      priority: 72,
      buttonText: 'Read the story',
      buttonLink: '/about',
      sectionId: '',
    },
  },
];

const TEMPLATE_MAP = new Map(ANNOUNCEMENT_TEMPLATES.map((template) => [template.key, template]));

const normalizePlacementValue = (value) => {
  const normalized = String(value || '').trim().toUpperCase();
  if (normalized === 'HEADER_DROPDOWN') return 'CATEGORY_DROPDOWN';
  return normalized;
};

const isTemplateCompatible = (template, context = {}) => {
  if (!template) return false;
  const location = normalizePlacementValue(context.displayLocation);
  const style = normalizePlacementValue(context.displayStyle);

  if (location && normalizePlacementValue(template.displayLocation) !== location) {
    return false;
  }

  if (style && normalizePlacementValue(template.displayStyle) !== style) {
    return false;
  }

  return true;
};

const DEFAULT_TEMPLATE_KEYS = {
  'HEADER:BANNER': 'header-free-shipping',
  'HEADER:POPUP': 'header-free-shipping',
  'HEADER:MODAL': 'header-free-shipping',
  'HEADER:SLIDE_IN': 'header-free-shipping',
  'HEADER:STICKY': 'header-free-shipping',
  'CATEGORY_DROPDOWN:BANNER': 'header-category-dropdown-highlight',
  'HOMEPAGE:BANNER': 'homepage-hero-promo',
  'HOMEPAGE:POPUP': 'homepage-welcome-popup',
  'HOMEPAGE:MODAL': 'homepage-coupon-modal',
  'HOMEPAGE:SLIDE_IN': 'homepage-giveaway-slide-in',
  'HOMEPAGE:STICKY': 'homepage-community-sticky',
  'PRODUCT_PAGES:BANNER': 'product-bundle-offer',
  'PRODUCT_PAGES:POPUP': 'product-size-guide-popup',
  'PRODUCT_PAGES:MODAL': 'product-detail-modal',
  'PRODUCT_PAGES:SLIDE_IN': 'product-low-stock-slide',
  'PRODUCT_PAGES:STICKY': 'product-assurance-sticky',
  'CATEGORIES:BANNER': 'category-hero-banner',
  'CATEGORIES:POPUP': 'category-discovery-popup',
  'CATEGORIES:MODAL': 'category-guide-modal',
  'CATEGORIES:SLIDE_IN': 'category-offer-slide-in',
  'CATEGORIES:STICKY': 'category-assurance-sticky',
  'CHECKOUT:BANNER': 'checkout-shipping-deadline',
  'CHECKOUT:POPUP': 'checkout-support-popup',
  'CHECKOUT:MODAL': 'checkout-upsell-modal',
  'CHECKOUT:SLIDE_IN': 'checkout-support-slide',
  'CHECKOUT:STICKY': 'checkout-trust-sticky',
  'ALL:BANNER': 'global-support-banner',
  'ALL:POPUP': 'global-app-download',
  'ALL:MODAL': 'global-newsletter-modal',
  'ALL:SLIDE_IN': 'global-help-slide-in',
  'ALL:STICKY': 'global-seasonal-campaign',
  'SECTION:BANNER': 'section-featured-collections-card',
};

export function getDefaultAnnouncementTemplateKey(displayLocation = 'HEADER', displayStyle = 'BANNER') {
  const normalizedLocation = normalizePlacementValue(displayLocation) || 'HEADER';
  let normalizedStyle = normalizePlacementValue(displayStyle) || 'BANNER';

  if (normalizedLocation === 'HEADER' || normalizedLocation === 'SECTION' || normalizedLocation === 'CATEGORY_DROPDOWN') {
    normalizedStyle = 'BANNER';
  }

  return DEFAULT_TEMPLATE_KEYS[`${normalizedLocation}:${normalizedStyle}`] || 'global-support-banner';
}

export function getAnnouncementTemplate(templateKey, context = {}) {
  if (templateKey && TEMPLATE_MAP.has(templateKey)) {
    const template = TEMPLATE_MAP.get(templateKey);
    if (isTemplateCompatible(template, context)) {
      return template;
    }
    if (!context.displayLocation && !context.displayStyle) {
      return template;
    }
  }

  const fallbackTemplate = TEMPLATE_MAP.get(
    getDefaultAnnouncementTemplateKey(context.displayLocation, context.displayStyle)
  );

  if (isTemplateCompatible(fallbackTemplate, context)) {
    return fallbackTemplate;
  }

  const compatibleTemplate = ANNOUNCEMENT_TEMPLATES.find((template) => isTemplateCompatible(template, context));
  return compatibleTemplate || fallbackTemplate || ANNOUNCEMENT_TEMPLATES[0];
}

export function resolveAnnouncementTemplateKey(announcement = {}) {
  return getAnnouncementTemplate(announcement.templateKey, announcement).key;
}

export function createAnnouncementFromTemplate(templateKey, overrides = {}) {
  const template = getAnnouncementTemplate(templateKey);
  return {
    ...template.defaults,
    templateKey: template.key,
    ...overrides,
  };
}

export function getAnnouncementTemplatesForGroup(group = 'all') {
  if (!group || group === 'all') {
    return ANNOUNCEMENT_TEMPLATES;
  }

  return ANNOUNCEMENT_TEMPLATES.filter((template) => template.group === group);
}

export function getAnnouncementTemplatesForPlacement(displayLocation, displayStyle) {
  if (!displayLocation) {
    return ANNOUNCEMENT_TEMPLATES;
  }

  return ANNOUNCEMENT_TEMPLATES.filter((template) => (
    template.displayLocation === displayLocation
    && (!displayStyle || template.displayStyle === displayStyle)
  ));
}
